# Site settings
title: Siddhant
description: Siddhant
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Siddhant Verma
user_description: Junior Undergraduate student at Delhi Technological University with Electronics as a major.
user_title:
email: siddhantverma777@gmail.com
twitter_username: siddhantv10
github_username:  siddhantv10
gplus_username:  siddhantverma777

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
